package com.codeformas.edu.v1.repository;

import com.codeformas.edu.v1.model.CourseTypesEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 28/06/2019
*/
@Repository
public interface CourseTypesEntityRepository extends JpaRepository<CourseTypesEntity, Integer> {

}
