package com.codeformas.edu.managers;

import com.codeformas.edu.model.AccountPypesEntity;
import com.codeformas.edu.repository.AccountPypesEntityRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 28/06/2019
*/
@Component
public class AccountPypesEntityManager {

	private AccountPypesEntityRepository accountPypesEntityRepository;

	@Autowired
	public AccountPypesEntityManager(AccountPypesEntityRepository accountPypesEntityRepository) {
		this.accountPypesEntityRepository = accountPypesEntityRepository;
	}

}
