package com.codeformas.edu.managers;

import com.codeformas.edu.model.CourseTypesEntity;
import com.codeformas.edu.repository.CourseTypesEntityRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 28/06/2019
*/
@Component
public class CourseTypesEntityManager {

	private CourseTypesEntityRepository courseTypesEntityRepository;

	@Autowired
	public CourseTypesEntityManager(CourseTypesEntityRepository courseTypesEntityRepository) {
		this.courseTypesEntityRepository = courseTypesEntityRepository;
	}

}
