package com.codeformas.edu.managers;

import com.codeformas.edu.model.CourseAccountsEntity;
import com.codeformas.edu.repository.CourseAccountsEntityRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 28/06/2019
*/
@Component
public class CourseAccountsEntityManager {

	private CourseAccountsEntityRepository courseAccountsEntityRepository;

	@Autowired
	public CourseAccountsEntityManager(CourseAccountsEntityRepository courseAccountsEntityRepository) {
		this.courseAccountsEntityRepository = courseAccountsEntityRepository;
	}

}
