package com.codeformas.edu.managers;

import com.codeformas.edu.model.WayPaysEntity;
import com.codeformas.edu.repository.WayPaysEntityRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 28/06/2019
*/
@Component
public class WayPaysEntityManager {

	private WayPaysEntityRepository wayPaysEntityRepository;

	@Autowired
	public WayPaysEntityManager(WayPaysEntityRepository wayPaysEntityRepository) {
		this.wayPaysEntityRepository = wayPaysEntityRepository;
	}

}
